os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -scheme "CI" -sdk iphonesimulator -destination  "platform=iOS Simulator,OS=14.2,name=iPhone 11" ONLY_ARCHIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
